"""Request and response schemas for API endpoints."""

from pydantic import BaseModel

from models import CharacterAgentConfig


class CharacterCreate(BaseModel):
    """Request body for POST /api/v1/characters.

    UUID must not be provided - it will be auto-generated by the server.
    """

    name: str
    description: str
    role: str
    motivations: str
    relationships: str
    backstory: str
    agent_config: CharacterAgentConfig | None = None


class CharacterUpdate(BaseModel):
    """Request body for PUT /api/v1/characters/{id}.

    UUID in body is ignored - the path parameter takes precedence.
    """

    name: str
    description: str
    role: str
    motivations: str
    relationships: str
    backstory: str
    agent_config: CharacterAgentConfig | None = None
